### ISSUE TITLE
Goto exception are redefined in the same module

### ISSUE THREAD

**Issue by jorisgio** [ygrek/ragel#2]
exception Goto_match can be emited multiple times to the same compiled file and it fails to build on ocaml 4.03. 
```
Error: Multiple definition of the extension constructor name Goto_match.
       Names must be unique in a given structure or signature.
```

**Comment by ygrek** [comment]
Fixed in https://github.com/cyberhuman/ragel-old/commit/8059a490235f23e1d64f62116db5afbd0b1cc9fd
